### ISSUE TITLE
403 forbidden since late Dec 2018 - user agent problem?

### ISSUE THREAD

**Issue by linuxrecon** [lx4r/chames#17]
Since late December 2018, the following error does always occur for each entry added when browsing through chames:  file_get_contents(https://www.g2a.com/marketplace/product/auctions/?id=<insert your id here>): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden in /www/htdocs/<user>/<url>/utils/get_game_data.php on line 7

If you visit the URL with your browser, the output is fine (JSON output).  However, trying to do a curl or wget from command line on the URLs does result in: "You don't have permission to access "http&#58;&#47;&#47;www&#46;g2a&#46 ......" so I guess that might be a useragent thing or something? I tried to set the useragent with curl but unfortunately, the error persists. Tested with multiple IP addresses and different setups (dedicated Debian / Apache setup as well as shared hosting service).

**Comment by lx4r** [comment]
@linuxrecon Thanks for reporting this issue, I will look into it when I find the time. Unfortunately I'm quite busy with university right now so this could take a while, sorry.
If someone else finds a solution I'd be happy too of course :).

**Comment by m-villalilla** [comment]
I found out that it works with wget if you modify the http header by setting the "accept-language"-attribute.
For example `wget --header='accept-language: *' URL` works for me, I think G2A checks for this attribute and returns 403 Forbidden if it is missing.
Since my knowledge in PHP is limited, I was not able to make it work with file_get_contents, but this might help you or someone else to fix the issue.
